services:
    mysqldb:
        image: mysql:8.0.34
        container_name: mysqlcontainer
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - D:\API\dbinit\init.sql:/docker-entrypoint-initdb.d/init.sql
            - $HOME/database:/var/lib/mysql
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: "3t"
            MYSQL_ROOT_USER: "root"
            MYSQL_ROOT_PASSWORD: "trantuanthinh"
            SERVICE_TAG: "dev"
            SERVICE_NAME: "mysqldb"
        networks:
            - internalnet

networks:
    internalnet:
        driver: bridge
